# Generated by Django 5.0.4 on 2024-05-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=250, null=True)),
                ('firstName', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'non-binary')], max_length=10, null=True)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_country', to='UserApp.country')),
            ],
        ),
    ]
