# Generated by Django 5.0.4 on 2024-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uplaods/file/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
