# Generated by Django 5.0.4 on 2024-05-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_file', to='UserApp.customer'),
        ),
    ]
