# Generated by Django 5.0.4 on 2024-05-05 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_fileupload_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='customer',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='userfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_file', to='UserApp.customer'),
        ),
    ]
