# Generated by Django 5.0.4 on 2024-05-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_remove_fileupload_customer_fileupload_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='userfile',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='userImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_image', to='UserApp.customeuser'),
        ),
    ]
